---
# file: playbook-beats-output-logstash.yml

- hosts: ##targethost##
  remote_user: elastest
  become: yes
  roles:
    - .
# The installation state of the beats packages, passed to the appropriate
# packaging module (yum/apt) as the 'state'.
# Set to 'present' to install, 'latest' to upgrade and 'absent' to remove.

  vars:
    # The list of the packages managed by this role
    beats:
      - filebeat
      - topbeat
      - packetbeat
#      - metricbeat
    beats_package:
      - { 'name': 'filebeat', 'state': 'present', 'version': '1.2.3' }
      - { 'name': 'topbeat', 'state': 'present', 'version': '1.2.3' }
      - { 'name': 'packetbeat', 'state': 'present', 'version': '1.2.3' }
#      - { 'name': 'metricbeat', 'state': 'present', 'version': '1.2.3' }


# Repository url
    beats_repository_url: "https://packages.elastic.co/"

# GPG key url
    beats_repository_gpg_key_url: "https://packages.elastic.co/GPG-KEY-elasticsearch"

# Download specific versions of beats from this url (instead of install from repo).
# You can set here a specific url to download the beats packages directly from.
    beats_download_url: "https://artifacts.elastic.co/downloads/beats"
# List of specific beats version you want to download from beats_download_url.
    beats_download:
      - { "name": "filebeat", "version": "5.0.0", "state": "present" }
      - { "name": "packetbeat", "version": "5.0.0", "state": "present" }
#     - { "name": "metricbeat", "version": "5.0.0", "state": "present" }

# in version 5 appears metricbeat, previous version topbeat was used

# Start beats
    beats_start_filebeat: true
    beats_start_topbeat: true
    beats_start_packetbeat: true
#    beats_start_metricbeat: true
# Restart beats every hour
    beats_restart_filebeat: false
    beats_restart_topbeat: false
    beats_restart_packetbeat: false
#    beats_restart_metricbeat: false
# Trace beats open files every hour
    beats_trace_filebeat: false
    beats_trace_topbeat: false
    beats_trace_packetbeat: false
#    beats_trace_metricbeat: false
# Location of beats configurations loaded by the init script
    beats_init_config_directory: "/etc/sysconfig"

# Environment variable to set, they will be available in your beats configuration files
  # beats_environment:
  #  - { "name": "filebeat", "state": "present", "line": "FB_ENV=$(echo \"test\")" }

# list of host entries to add to or remove from /etc/hosts on beats servers.
# Set state to 'present' to add a line, or 'absent' to remove it.
# beats_hosts:
#   - { "line": "127.0.0.1 localhost elk sample", "state": "absent" }

# The contents of this variable will be placed into the `beats_ca_path`
# This should either be set to a string containing your CA certificate or
# use a lookup plugin to retrieve it.
#  ex:
#   beats_ca_cert: "{{ lookup('file', '/path/to/ca.crt') }}"
    beats_ca_cert: null

# Path to which the above certificate will be uploaded
    beats_ca_path: /etc/pki/tls/certs/beats.crt

# filebeat
# `beats_config_filebeat` is templated directly into filebeat.yml for the config.
# See https://github.com/elastic/beats/blob/master/filebeat/filebeat.yml for
# an exhaustive list of configurations.
    beats_config_filebeat:
      fields:
        exec: "##exec-id##"
        component: "##component-name##"
        stream: "##stream-filebeat##"
      fields_under_root: true      
      filebeat:
        prospectors:
          - paths:
            - /var/log/*.log
            - /var/log/*/*.log
            - ##filepaths-to-monitor##
      output:
        logstash:
#          hosts: ["172.17.0.5:5044"]
          hosts: ["##logstash-ip##:##logstash-port##"]
          index: "filebeat"
      logging:
        to_syslog: true
        level: error

# topbeat
# `beats_config_topbeat` is templated directly into topbeat.yml for the config.
# See https://github.com/elastic/beats/blob/1.3/topbeat/etc/topbeat.yml for
# an exhaustive list of configurations.
    beats_config_topbeat:
      fields:
        exec: "##exec-id##"
        component: "##component-name##"
        stream: "##stream-topbeat##"
      fields_under_root: true
      input:
        procs: [".*"]
        stats:
          system: true
          process: true
          filesystem: true
          cpu_per_core: false
      output:
        logstash:
#          hosts: ["172.17.0.5:5044"]
          hosts: ["##logstash-ip##:##logstash-port##"]
          index: "topbeat"
      logging:
        to_syslog: true
        level: error

# packetbeat
# `beats_config_packetbeat` is templated directly into packetbeat.yml for the config.
# See https://github.com/elastic/beats/blob/master/packetbeat/packetbeat.yml for
# an exhaustive list of configurations.
    beats_config_packetbeat:
      fields:
        exec: "##exec-id##"
        component: "##component-name##"
        stream: "##stream-packetbeat##"
      fields_under_root: true
      interfaces:
        device: any
      protocols:
        dns:
            include_additionals: true
            include_authorities: true
            ports:
            - 53
        http:
            ports:
            - 80
            - 8080
        memcache:
            ports:
            - 11211
        mongodb:
            ports:
            - 27017
        mysql:
            ports:
            - 3306
        pgsql:
            ports:
            - 5432
        redis:
            ports:
            - 6379
        thrift:
            ports:
            - 9090
      output:
        logstash:
#          hosts: ["172.17.0.5:5044"]
          hosts: ["##logstash-ip##:##logstash-port##"]
          index: "packetbeat"
      logging:
          to_syslog: true
          level: error

# metricbeat
# `beats_config_metricbeat` is templated directly into metricbeat.yml for the config.
# See https://github.com/elastic/beats/blob/master/metricbeat/metricbeat.yml for
# an exhaustive list of configurations.
#    beats_config_metricbeat:
#      metricbeat.modules:
#        - module: system
#          metricsets:
#            - cpu
#            - load
#            - filesystem
#            - fsstat
#            - memory
#            - network
#            - process
#      enabled: true
#      period: 10s
#      processes: ['.*']
#      output:
#        file:
#          path: /tmp/metricbeat
#          filename: metricbeat.out
#      logging:
#        to_syslog: true
#        level: error


  tasks:
    - include: tasks/main.yml
  handlers:
    - include: handlers/main.yml
